# Krushr Project Management Platform
# Docker Compose configuration for development and production

version: '3.8'

services:
  # Main application
  krushr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/database.db
      - JWT_SECRET=your-super-secure-jwt-secret-change-in-production
      - HOST=0.0.0.0
      - PORT=3002
      - MAX_FILE_SIZE=10485760
    volumes:
      - krushr_data:/app/api/data
      - krushr_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy with SSL
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - krushr_ssl:/etc/nginx/ssl
    depends_on:
      - krushr
    restart: unless-stopped
    profiles:
      - production

  # Optional: Redis for caching (uncomment when needed)
  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - krushr_redis:/data
  #   restart: unless-stopped
  #   profiles:
  #     - production

volumes:
  krushr_data:
    driver: local
  krushr_uploads:
    driver: local
  krushr_ssl:
    driver: local
  # krushr_redis:
  #   driver: local

networks:
  default:
    name: krushr_network