#!/bin/bash
# Claude Code Automation Startup Script
# Generated by setup-claude-automation.js

PROJECT_ROOT="/Users/justindoff/Cursor Projects/krushr-clean"
ORCHESTRATOR_PATH="/Users/justindoff/Cursor Projects/krushr-clean/Github-CC-Research/claudecode-orchestrator"
AUTO_ACTION_PATH="/Users/justindoff/Cursor Projects/krushr-clean/Github-CC-Research/claude-code-auto-action"

echo "🚀 Starting Claude Code Automation..."

# Start orchestrator
echo "🎭 Starting orchestrator..."
cd "$ORCHESTRATOR_PATH"
npm start &
ORCHESTRATOR_PID=$!

# Start auto-action system
echo "⚡ Starting auto-action system..."
cd "$AUTO_ACTION_PATH"
./scripts/setup-auto-mode.sh &
AUTO_ACTION_PID=$!

echo "✅ Claude Code Automation started successfully!"
echo "   Orchestrator PID: $ORCHESTRATOR_PID"
echo "   Auto-action PID: $AUTO_ACTION_PID"

# Save PIDs for cleanup
echo "$ORCHESTRATOR_PID" > /tmp/claude-orchestrator.pid
echo "$AUTO_ACTION_PID" > /tmp/claude-auto-action.pid

echo "💡 Use 'npm run claude:stop' to stop all automation processes"
