#!/bin/bash
# Claude Code Automation Stop Script
# Generated by setup-claude-automation.js

echo "🛑 Stopping Claude Code Automation..."

# Stop orchestrator
if [ -f /tmp/claude-orchestrator.pid ]; then
    ORCHESTRATOR_PID=$(cat /tmp/claude-orchestrator.pid)
    kill $ORCHESTRATOR_PID 2>/dev/null || true
    rm /tmp/claude-orchestrator.pid
    echo "   🎭 Orchestrator stopped"
fi

# Stop auto-action
if [ -f /tmp/claude-auto-action.pid ]; then
    AUTO_ACTION_PID=$(cat /tmp/claude-auto-action.pid)
    kill $AUTO_ACTION_PID 2>/dev/null || true
    rm /tmp/claude-auto-action.pid
    echo "   ⚡ Auto-action stopped"
fi

echo "✅ Claude Code Automation stopped successfully!"
